### ISSUE TITLE
All Websites, except one, do not work anymore!

### ISSUE THREAD

**Issue by Zirkulator** [NguyenDanPhuong/MangaRipper#108]
**All tested with Version 1.0.264. 
Tried to get ''Blood Lad'' Manga Chapters 66-70 from all of the pages.**

batoto.to:
Page needs User-Registration

mangafox.me:
[System.Net.Http]
Invalid Url

mangahere.co:
Parse content failed! Please check...
[Manga Ripper Core]

kissmanga.com:
Download cancelled! Reason: Cannot decrypt image URIs.

mangareader.net:
works mostly well (for gods sake...)

mangastream: (Tried a ''Fairy Tail'' chapter, they doesn't have ''Blood Lad''.
Cannot find service to download from input site
[Manga Ripper Core]

readcomics.tv
Website doesn't exist anymore

Tested on 05.12.2017

**Comment by GambitKZ** [comment]
> batoto.to:
> Page needs User-Registration
Well, you really need to have an account in Bato.to for downloads. Paste it into "MangaRipper.Configuration.json" file:
![image](https://user-images.githubusercontent.com/17333840/33673333-a5fe028c-dad6-11e7-8178-2977efa5c87a.png)
![image](https://user-images.githubusercontent.com/17333840/33673374-bfa4e642-dad6-11e7-9091-1f60cb0d472a.png)

> mangafox.me:
> [System.Net.Http]
> Invalid Url
I can't open "mangafox.me", instead I have been redirected to "mangafox.la". Did they change the address? Can someone clarify? 
If it was moved, then we need just change the address of the website in the code.

> mangahere.co:
> Parse content failed! Please check...
> [Manga Ripper Core]
Get the same error. We should check the logic.

> kissmanga.com:
> Download cancelled! Reason: Cannot decrypt image URIs.
Looks like we still have an issue with encryption on the website

> mangastream: (Tried a ''Fairy Tail'' chapter, they doesn't have ''Blood Lad''.
> Cannot find service to download from input site
> [Manga Ripper Core]
Once again, because of the website url. It gives me - http://readms.net/
And yeah, could someone clarify this?

> readcomics.tv
> Website doesn't exist anymore
R.I.P.

**Comment by NguyenDanPhuong** [comment]
I've fixed all but KissManga. Please check the latest version :)
