### ISSUE TITLE
MangaRipper download failed, says virus detected by Windows Defender

### ISSUE THREAD

**Issue by AlexGZA** [NguyenDanPhuong/MangaRipper#121]
This only happened when I tried to download a newer version of MangaRipper, as I was content with using version 1.0.285, as that was the latest version at the time until I had some issues with downloading. I tried to download the latest version of MangaRipper as of December 30th, 2017, but WindowDefender blocked the download, claiming that a virus was detected. What may be causing this detection? and how can I work around it to download MangaRipper?

**Comment by PrimordialHelios** [comment]
I also have this issue, came here to confirm the bug. Running MR 1.0.317 on Windows 10 version 1709 build 16299.125 gives the error message "The operation could not complete successfully because the file contains a virus or potentially unwanted software".

As a temporary workaround, opening Windows Defender's control panel, clicking "Virus & threat protection", then "Virus & threat protection settings", then "Add or remove exclusions" and excluding the MR folder (not the file, the entire folder) will allow the program to run.

**Comment by AccelerateIzaya** [comment]
Same issue here. *~*

**Comment by NguyenDanPhuong** [comment]
I've submitted the file to Microsoft as false positive. Let's wait for them to update the definition.

https://www.microsoft.com/en-us/wdsi/submission/c93abcd9-77d1-4d94-a641-b56d470b26c8

**Comment by NguyenDanPhuong** [comment]
No longer happened for me. :)
