### ISSUE TITLE
Save to problem 

### ISSUE THREAD

**Issue by BaganLee** [NguyenDanPhuong/MangaRipper#17]
Hello again i have find something with to where the folders going to save when you change the directory before you add the files you want to download from a manga the directory change but when you change it after it saves the file to the last directory you save something.

Edit: I just mention the problem i don't want you to fix atm but when you have time or when you are going to release the next update

**Comment by NguyenDanPhuong** [comment]
Thank you for reporting. :)

Actually this is by design. The save to folder means to set when adding chapters to download list. But there's definite a problem with the UI confusing user. I will change them.

- Move "Add Chapters" button below Save To and Save As. So user knows Save To And Save As 'used' when adding chapters.
- Add Save To column in the download list.

If you have any suggest for improvement. Please let me know.

**Comment by NguyenDanPhuong** [comment]
I've fixed this one.
