### ISSUE TITLE
Save as PDF

### ISSUE THREAD

**Issue by coczero** [NguyenDanPhuong/MangaRipper#40]
It would be very useful to me to put the downloaded images directly into a pdf.
Ne old MangaRipper had that functionality and I always used it.
Might be cool to have the choice between each chapter into its own pdf or all chapters into one.

**Comment by iYatsumi** [comment]
You could try the alternative which is saving it as .CBZ, it is similar to the PDF format which saves every chapters into one file. 

You will need the app called cdisplay in order to read the .cbz format though which is free. 
It is pretty easy to use and has more options than the Adobe Reader. Try it out ! 
- http://www.cdisplay.me/

**Comment by coczero** [comment]
Very late response, I know... 
I want to read the downloaded Manga on a Kindle.
As far as I know, Kindle supports cbz, but it would be nice if there would be a built-in way to put all downloaded chapters into one file.

**Comment by MuminekM** [comment]
Another late reply - you can use Kindle Comic Converter to convert downloaded manga by MangaRipper to format supported by Kindle (cbz, mobi).
