### ISSUE TITLE
download the chapters to folder with the manga name

### ISSUE THREAD

**Issue by MarioNagi** [NguyenDanPhuong/MangaRipper#58]
i would like to thank you for your great work :D but i was wondering if you could make the program create a folder with the manga name and download the chapters in it which will make the viewing process much tidier thanks again :D

**Comment by JedBurke** [comment]
Not the dev, but was *just* thinking about how to implement it when I came across this. :p

**Comment by NguyenDanPhuong** [comment]
@JedBurke I think about grouping folder by prefix. :) However, this task is low priority because it can be done quite of easy outside MangaRipper.

**Comment by JedBurke** [comment]
@NguyenDanPhuong Indeed, it is easy to do outside of MangaRipper. But sometimes if you download a lot, it would be nice if everything went into the folder without having to do anything else. :)

Since the last post, I've been working on something in the experimental branch. I won't make a pull request for it because I'm not sure everyone else will like or want it.

![Save destination](https://cloud.githubusercontent.com/assets/6389344/24362222/6f9f1d12-130c-11e7-8d38-c71432484058.JPG)

^ You have two download locations. The top one is the 'Save to' location like before and the bottom is one for the series. If the user selects 'Series-Specific Destination', the application will create a folder 'D:\Hantsu x Trash' and download the chapters there for 'Hantsu x Trash'. The user can choose where to download the chapter by using the radio buttons. When the chapters are retrieved and the series folder exists, it will switch to that series' folder automatically. It still needs work as it only works for one series at a time.

**Comment by MarioNagi** [comment]
amazing work @JedBurke i will use this feature. Many thanks for your support :D

**Comment by JedBurke** [comment]
@MarioNagi Thank you for your kind words. :)

**Comment by GambitKZ** [comment]
@JedBurke 
b.t.w. I'm also interested in this behavior. So please, do a pull request.

**Comment by JedBurke** [comment]
@GambitKZ All right, but please give me some time to port it to the official codebase.
