### ISSUE TITLE
MangaRipper.Configuration.json not being read?

### ISSUE THREAD

**Issue by AlexGZA** [NguyenDanPhuong/MangaRipper#92]
KissManga does not work for me and every time I attempt to download something, I get an error saying "Cannot decrypt image URLs". Reading through the FAQ, I realized that I am to get the decrypted keys myself through some simple steps done in Chrome and Notepad. However, after I save and exit the file, I was still unable to get KissManga to work, which puzzled me, because it wasn't a problem with the program, as other websites, such as MangaFox, worked flawlessly. So then I used typed in my Batoto account in the .json to see if it is a problem with KissManga or something with the .json. And in the end, Batoto ended up with similar results, saying: "Parse content failed! Please check if you can access this content on your browser." At this point, my conclusion is that the .json config is simply not being read by the application if that is how it even works. I am no expert at all in this field of problems, so any help would be appreciated. I have attached the .json and logs file, see if it helps. (Note: I have deleted my password from the files)
[files.zip](https://github.com/NguyenDanPhuong/MangaRipper/files/1279517/files.zip)

**Comment by JedBurke** [comment]
I can't comment on how the Batoto plugin works.

As of the most recent updates, the KissManga plugin does indeed ignore the configuration file as it instead attempts to collect it from the page itself. See issue #46 for more. However, there was a change in the website which broke the implementation.

I've attached a [temporary fix](https://github.com/NguyenDanPhuong/MangaRipper/files/1283077/KM_Update.zip) for the plugin. Right-click the zip file for 'Properties' and click 'Unblock' if necessary. Finally extract the files into the MangaRipper/Plugins folder.

**Comment by AlexGZA** [comment]
Unfortunately, after downloading the temporary fix, and using it on the latest build of the program, I received the same error message. However, unlike issue #91, other websites such as Mangafox worked just fine. As a non-tech savvy, looking at codes and logs don't ring any bells for me, so all I can hope for now is for the developers to find a solution. Still, you have my thanks for attempting to fix this problem.

**Comment by JedBurke** [comment]
@AlexGZA It's no problem. For reasons mentioned there, I believe the error is within regards to KissManga and not MangaFox as the title states.

It's both unfortunate and strange that you and @BaganLee aren't receiving any satisfaction. I was able to retrieve a list of the image URLs for *The Devil is a Part-Timer!* and download the full chapter of *Gangsta.* on Windows 10 and 8 respectively. There appears to be something else at play which isn't evident on my side at the moment. Again I'm sorry I couldn't be of more assistance to both of you.

**Comment by JedBurke** [comment]
@BaganLee @AlexGZA 

> …which isn't evident on my side at the moment…

Raised my death flag and subsequently fell into the hole with that statement.

All right, after multiple tests, it appears that the pages are served differently or are just different. Sometimes the decryption keys are listed and other times they aren't. When they are listed, they could be split into multiple lines or contained in one. I don't know what triggers it, it *appears* to be random. 

Therefore with the behavior noted, the original plugin works sometimes and fails other occasions. Same could be said for the update. Noting this, I've tried to account for the possible differences instead of just throwing an error and quitting the download.

If you would be willing, please test the latest update. New logging is also in place to gather more information of failures. Please upload the log in the event that happens.

[MangaRipper.Plugin.KissManga.dll.zip](https://github.com/NguyenDanPhuong/MangaRipper/files/1307957/MangaRipper.Plugin.KissManga.dll.zip)

**Comment by AlexGZA** [comment]
Thank you very much for revisiting this issue, I have downloaded the updated plugin and to my surprise, it worked! I am not sure of the changes that were made to the files, but I can now confirm that the plugin is working and I am now able to download from KissManga, thank you very much. I cannot express my appreciation enough.

I will still attach my log file for the download in case it may contain any useful data.
[2017-09-18.zip](https://github.com/NguyenDanPhuong/MangaRipper/files/1311647/2017-09-18.zip)

**Comment by JedBurke** [comment]
I'm glad I could be of assistance and thank you for uploading your log as well.
